"""empty message

Revision ID: 3b958f92a364
Revises: 24e5189fda0a
Create Date: 2020-12-26 12:37:58.454305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b958f92a364'
down_revision = '24e5189fda0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocksOwned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lockname', sa.String(length=64), nullable=True),
    sa.Column('ownedBy', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LocksOwned_lockname'), 'LocksOwned', ['lockname'], unique=False)
    op.create_index(op.f('ix_LocksOwned_ownedBy'), 'LocksOwned', ['ownedBy'], unique=False)
    op.create_table('Reccomended Tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('basedIn', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', 'url')
    )
    op.create_index(op.f('ix_Reccomended Tools_basedIn'), 'Reccomended Tools', ['basedIn'], unique=False)
    op.create_index(op.f('ix_Reccomended Tools_company'), 'Reccomended Tools', ['company'], unique=True)
    op.create_index(op.f('ix_Reccomended Tools_url'), 'Reccomended Tools', ['url'], unique=False)
    op.create_table('LocksForSale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lockname', sa.String(length=64), nullable=True),
    sa.Column('ownedBy', sa.String(length=64), nullable=True),
    sa.Column('LfS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['LfS'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LocksForSale_lockname'), 'LocksForSale', ['lockname'], unique=False)
    op.create_index(op.f('ix_LocksForSale_ownedBy'), 'LocksForSale', ['ownedBy'], unique=False)
    op.create_table('LocksOnLoan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lockname', sa.String(length=64), nullable=True),
    sa.Column('ownedBy', sa.String(length=64), nullable=True),
    sa.Column('loanedTo', sa.String(length=64), nullable=True),
    sa.Column('LoL', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['LoL'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LocksOnLoan_loanedTo'), 'LocksOnLoan', ['loanedTo'], unique=False)
    op.create_index(op.f('ix_LocksOnLoan_lockname'), 'LocksOnLoan', ['lockname'], unique=False)
    op.create_index(op.f('ix_LocksOnLoan_ownedBy'), 'LocksOnLoan', ['ownedBy'], unique=False)
    op.create_table('UserBelts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belt_name', sa.String(length=16), nullable=True),
    sa.Column('UsrBelt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UsrBelt'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserBelts_belt_name'), 'UserBelts', ['belt_name'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_locks_owned_lockname', table_name='locks_owned')
    op.drop_index('ix_locks_owned_ownedBy', table_name='locks_owned')
    op.drop_table('locks_owned')
    op.drop_table('user_role')
    op.drop_index('ix_locks_for_sale_lockname', table_name='locks_for_sale')
    op.drop_index('ix_locks_for_sale_ownedBy', table_name='locks_for_sale')
    op.drop_table('locks_for_sale')
    op.drop_index('ix_locks_on_loan_loanedTo', table_name='locks_on_loan')
    op.drop_index('ix_locks_on_loan_lockname', table_name='locks_on_loan')
    op.drop_index('ix_locks_on_loan_ownedBy', table_name='locks_on_loan')
    op.drop_table('locks_on_loan')
    op.drop_index('ix_user_belt_belt_name', table_name='user_belt')
    op.drop_table('user_belt')
    op.drop_index('ix_res_tool_basedIn', table_name='res_tool')
    op.drop_index('ix_res_tool_company', table_name='res_tool')
    op.drop_index('ix_res_tool_url', table_name='res_tool')
    op.drop_table('res_tool')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('res_tool',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('basedIn', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'url', name='res_tool_pkey')
    )
    op.create_index('ix_res_tool_url', 'res_tool', ['url'], unique=False)
    op.create_index('ix_res_tool_company', 'res_tool', ['company'], unique=True)
    op.create_index('ix_res_tool_basedIn', 'res_tool', ['basedIn'], unique=False)
    op.create_table('user_belt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('belt_name', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('UsrBelt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UsrBelt'], ['user.id'], name='user_belt_UsrBelt_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_belt_pkey')
    )
    op.create_index('ix_user_belt_belt_name', 'user_belt', ['belt_name'], unique=False)
    op.create_table('locks_on_loan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lockname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ownedBy', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('loanedTo', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('LoL', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LoL'], ['user.id'], name='locks_on_loan_LoL_fkey'),
    sa.PrimaryKeyConstraint('id', name='locks_on_loan_pkey')
    )
    op.create_index('ix_locks_on_loan_ownedBy', 'locks_on_loan', ['ownedBy'], unique=False)
    op.create_index('ix_locks_on_loan_lockname', 'locks_on_loan', ['lockname'], unique=False)
    op.create_index('ix_locks_on_loan_loanedTo', 'locks_on_loan', ['loanedTo'], unique=False)
    op.create_table('locks_for_sale',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lockname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ownedBy', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('LfS', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['LfS'], ['user.id'], name='locks_for_sale_LfS_fkey'),
    sa.PrimaryKeyConstraint('id', name='locks_for_sale_pkey')
    )
    op.create_index('ix_locks_for_sale_ownedBy', 'locks_for_sale', ['ownedBy'], unique=False)
    op.create_index('ix_locks_for_sale_lockname', 'locks_for_sale', ['lockname'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_role_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_role_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_role_pkey')
    )
    op.create_table('locks_owned',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lockname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('ownedBy', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='locks_owned_pkey')
    )
    op.create_index('ix_locks_owned_ownedBy', 'locks_owned', ['ownedBy'], unique=False)
    op.create_index('ix_locks_owned_lockname', 'locks_owned', ['lockname'], unique=False)
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_UserBelts_belt_name'), table_name='UserBelts')
    op.drop_table('UserBelts')
    op.drop_index(op.f('ix_LocksOnLoan_ownedBy'), table_name='LocksOnLoan')
    op.drop_index(op.f('ix_LocksOnLoan_lockname'), table_name='LocksOnLoan')
    op.drop_index(op.f('ix_LocksOnLoan_loanedTo'), table_name='LocksOnLoan')
    op.drop_table('LocksOnLoan')
    op.drop_index(op.f('ix_LocksForSale_ownedBy'), table_name='LocksForSale')
    op.drop_index(op.f('ix_LocksForSale_lockname'), table_name='LocksForSale')
    op.drop_table('LocksForSale')
    op.drop_index(op.f('ix_Reccomended Tools_url'), table_name='Reccomended Tools')
    op.drop_index(op.f('ix_Reccomended Tools_company'), table_name='Reccomended Tools')
    op.drop_index(op.f('ix_Reccomended Tools_basedIn'), table_name='Reccomended Tools')
    op.drop_table('Reccomended Tools')
    op.drop_index(op.f('ix_LocksOwned_ownedBy'), table_name='LocksOwned')
    op.drop_index(op.f('ix_LocksOwned_lockname'), table_name='LocksOwned')
    op.drop_table('LocksOwned')
    # ### end Alembic commands ###
