"""updated roles table, added userRoles table

Revision ID: d60f8c630c00
Revises: da23ebb6634a
Create Date: 2020-12-26 10:03:27.129410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60f8c630c00'
down_revision = 'da23ebb6634a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('role', sa.Column('name', sa.String(length=42), nullable=True))
    op.drop_constraint('user_users_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_users_id_fkey', 'user', 'role', ['users_id'], ['id'])
    op.drop_column('role', 'name')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
